### PR TITLE
Simplify inspect()

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This PR simplifies the `inspect` function by removing merging to cases of the if-statement.

### CODE REVIEW

**Comment by marvinhagemeister** [comment]
Looks like travis is missing the environment variables for sourcelabs.

**Comment by squidfunk** [comment]
Travis doesn't expose secure variables in PRs, at least when they are set via the settings. I have to investigate whether this is the same behavior when encoding them inside the `.travis.yml`.

BTW: Thanks for your PRs!

**Comment by squidfunk** [comment]
This is not possible at all, so no tests for external PRs:
https://blog.travis-ci.com/2013-06-10-secure-env-in-pull-requests/

**Comment by marvinhagemeister** [comment]
I see, thanks for the heads up 👍

**Pull request merged**
